<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit307b5b88de8881bee080533a7d150cf4
{
    public static $prefixLengthsPsr4 = array (
        'B' => 
        array (
            'Blocktrail\\CryptoJSAES\\' => 23,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Blocktrail\\CryptoJSAES\\' => 
        array (
            0 => __DIR__ . '/..' . '/blocktrail/cryptojs-aes-php/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit307b5b88de8881bee080533a7d150cf4::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit307b5b88de8881bee080533a7d150cf4::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit307b5b88de8881bee080533a7d150cf4::$classMap;

        }, null, ClassLoader::class);
    }
}
