<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Blocktrail\\CryptoJSAES\\' => array($vendorDir . '/blocktrail/cryptojs-aes-php/src'),
);
